config/routes.rb
RaichandApp::Application.routes.draw do
  resources :categories

  resources :suggestions

  resources :raichands

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/raichand.rb
class Raichand < ActiveRecord::Base
has_many :suggestions
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
belongs_to :raichand
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/raichands_controller.rb
class RaichandsController < ApplicationController
  # GET /raichands
  # GET /raichands.xml
  def index
    @raichands = Raichand.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @raichands }
    end
  end

  # GET /raichands/1
  # GET /raichands/1.xml
  def show
    @raichand = Raichand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @raichand }
    end
  end

  # GET /raichands/new
  # GET /raichands/new.xml
  def new
    @raichand = Raichand.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @raichand }
    end
  end

  # GET /raichands/1/edit
  def edit
    @raichand = Raichand.find(params[:id])
  end

  # POST /raichands
  # POST /raichands.xml
  def create
    @raichand = Raichand.new(params[:raichand])

    respond_to do |format|
      if @raichand.save
        format.html { redirect_to(@raichand, :notice => 'Raichand was successfully created.') }
        format.xml  { render :xml => @raichand, :status => :created, :location => @raichand }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @raichand.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /raichands/1
  # PUT /raichands/1.xml
  def update
    @raichand = Raichand.find(params[:id])

    respond_to do |format|
      if @raichand.update_attributes(params[:raichand])
        format.html { redirect_to(@raichand, :notice => 'Raichand was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @raichand.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /raichands/1
  # DELETE /raichands/1.xml
  def destroy
    @raichand = Raichand.find(params[:id])
    @raichand.destroy

    respond_to do |format|
      format.html { redirect_to(raichands_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  # GET /suggestions
  # GET /suggestions.xml
  def index
    @suggestions = Suggestion.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @suggestions }
    end
  end

  # GET /suggestions/1
  # GET /suggestions/1.xml
  def show
    @suggestion = Suggestion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @suggestion }
    end
  end

  # GET /suggestions/new
  # GET /suggestions/new.xml
  def new
    @suggestion = Suggestion.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @suggestion }
    end
  end

  # GET /suggestions/1/edit
  def edit
    @suggestion = Suggestion.find(params[:id])
  end

  # POST /suggestions
  # POST /suggestions.xml
  def create
    @suggestion = Suggestion.new(params[:suggestion])

    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to(@suggestion, :notice => 'Suggestion was successfully created.') }
        format.xml  { render :xml => @suggestion, :status => :created, :location => @suggestion }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @suggestion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /suggestions/1
  # PUT /suggestions/1.xml
  def update
    @suggestion = Suggestion.find(params[:id])

    respond_to do |format|
      if @suggestion.update_attributes(params[:suggestion])
        format.html { redirect_to(@suggestion, :notice => 'Suggestion was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @suggestion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions/1
  # DELETE /suggestions/1.xml
  def destroy
    @suggestion = Suggestion.find(params[:id])
    @suggestion.destroy

    respond_to do |format|
      format.html { redirect_to(suggestions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/raichands_helper.rb
module RaichandsHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.category %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @category.category %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RaichandApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/raichands/_form.html.erb
<%= form_for(@raichand) do |f| %>
  <% if @raichand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@raichand.errors.count, "error") %> prohibited this raichand from being saved:</h2>

      <ul>
      <% @raichand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/raichands/edit.html.erb
<h1>Editing raichand</h1>

<%= render 'form' %>

<%= link_to 'Show', @raichand %> |
<%= link_to 'Back', raichands_path %>

app/views/raichands/index.html.erb
<h1>Listing raichands</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @raichands.each do |raichand| %>
  <tr>
    <td><%= raichand.name %></td>
    <td><%= raichand.email %></td>
    <td><%= link_to 'Show', raichand %></td>
    <td><%= link_to 'Edit', edit_raichand_path(raichand) %></td>
    <td><%= link_to 'Destroy', raichand, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Raichand', new_raichand_path %>

app/views/raichands/new.html.erb
<h1>New raichand</h1>

<%= render 'form' %>

<%= link_to 'Back', raichands_path %>

app/views/raichands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @raichand.name %>
</p>

<p>
  <b>Email:</b>
  <%= @raichand.email %>
</p>


<%= link_to 'Edit', edit_raichand_path(@raichand) %> |
<%= link_to 'Back', raichands_path %>

app/views/suggestions/_form.html.erb
<%= form_for(@suggestion) do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% @suggestion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggestions/edit.html.erb
<h1>Editing suggestion</h1>

<%= render 'form' %>

<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<h1>Listing suggestions</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @suggestions.each do |suggestion| %>
  <tr>
    <td><%= suggestion.content %></td>
    <td><%= suggestion.user_id %></td>
    <td><%= suggestion.category_id %></td>
    <td><%= link_to 'Show', suggestion %></td>
    <td><%= link_to 'Edit', edit_suggestion_path(suggestion) %></td>
    <td><%= link_to 'Destroy', suggestion, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Suggestion', new_suggestion_path %>

app/views/suggestions/new.html.erb
<h1>New suggestion</h1>

<%= render 'form' %>

<%= link_to 'Back', suggestions_path %>

app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @suggestion.content %>
</p>

<p>
  <b>User:</b>
  <%= @suggestion.user_id %>
</p>

<p>
  <b>Category:</b>
  <%= @suggestion.category_id %>
</p>


<%= link_to 'Edit', edit_suggestion_path(@suggestion) %> |
<%= link_to 'Back', suggestions_path %>